# Generated by Django 5.1.7 on 2025-03-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['date_added'], 'verbose_name_plural': 'entries'},
        ),
    ]
